# MEGAZO RMF Door Parameters

doors:
  "XXXXXXXXXXXXXXXXXXX": # Insert door name here. It must mirror door name on RMF Traffic Editor.
    ICED_id: XXXXXXXXXXXXXXXXXXX
    door_signal_period: 3.0 # In seconds
    door_close_feature: True # True if door close API is available
  "XXXXXXXXXXXXXXXXXXX": # Insert door name here. It must mirror door name on RMF Traffic Editor.
    ICED_id: XXXXXXXXXXXXXXXXXXX
    door_signal_period: 3.0 # In seconds
    door_close_feature: True # True if door close API is available

api_endpoint: "https://www.evcard.cc:8181"
username: "XXXXXXXXXXXXXXXXXXX"
password: "XXXXXXXXXXXXXXXXXXX"

mqtt_endpoint: "www.evcard.cc"
mqtt_port: 8090
mqtt_password: 'XXXXXXXXXXXXXXXXXXX'
mqtt_client_id: 'XXXXXXXXXXXXXXXXXXX'
project_id: XXXXXXXXXXXXXXXXXXX
mqtt_topic: XXXXXXXXXXXXXXXXXXX

door_subscriber:
  topic_name: "adapter_door_requests"

door_publisher:
  topic_name: "door_states"
  door_state_publish_period: 1.0 # In seconds